package main

/*
This code was generated by mkparamfilefunc
with parameters:
command line:2: -funcs personalOnly


DO NOT EDIT
*/

import (
	"path/filepath"

	"github.com/nickwells/filecheck.mod/filecheck"
	"github.com/nickwells/param.mod/v3/param"
	"github.com/nickwells/xdg.mod/xdg"
)

/*
SetConfigFile adds a config file to the set which the param parser will process
before checking the command line parameters.
*/
func SetConfigFile(ps *param.PSet) error {
	baseDir := xdg.ConfigHome()

	ps.AddConfigFileStrict(
		filepath.Join(baseDir,
			"github.com",
			"nickwells",
			"utilities",
			"retirement",
			"common.cfg"),
		filecheck.Optional)
	return nil
}

