/*
The mkpkgerr command is intended for generating a package-specific error type
similar to the runtime.Error type. This allows users of your package to
explicitly identify errors that have been generated by the package.
*/
package main
